# Generated by Django 2.2.9 on 2020-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
